package entities;

import fileio.PlantInput;

/**
 * Represents a plant entity with growth stages and oxygen-producing capability.
 * A plant evolves through multiple maturity levels and has type-specific
 * characteristics such as oxygen output and probability of obstruction.
 */
public class Plant extends Entity {

    /** Magic number constants */
    private static final double GROWTH_INCREMENT = 0.2d;
    private static final double PERCENT_NORMALIZATION = 100d;

    /** The specific type of this plant. */
    private final PlantType type;

    /** The current maturity level of the plant. */
    private Maturity age = Maturity.Young;

    /** Progress toward the next maturity stage (0 to 1). */
    private double growthLevel = 0d;

    /**
     * Defines the various plant categories,
     * each with a base oxygen production value and a probability of getting stuck.
     */
    private enum PlantType {
        FloweringPlants(6d, 90),
        GymnospermsPlants(0d, 60),
        Ferns(0d, 30),
        Mosses(0.8, 40),
        Algae(0.5, 20);

        private final double oxygenPlant;
        private final double stuckProbability;

        PlantType(final double oxygenPlant, final double stuckProbability) {
            this.oxygenPlant = oxygenPlant;
            this.stuckProbability = stuckProbability;
        }

        /**
         * Returns the base oxygen produced by this plant type.
         *
         * @return oxygen output value
         */
        public double getOxygenPlant() {
            return oxygenPlant;
        }

        /**
         * Returns the probability (in percentage) that this plant gets stuck.
         *
         * @return stuck probability percentage
         */
        public double getStuckProbability() {
            return stuckProbability;
        }
    }

    /**
     * Represents the maturity levels of a plant,
     * each providing a bonus to oxygen generation.
     */
    private enum Maturity {
        Young(0.2),
        Mature(0.7),
        Old(0.4);

        private final double oxygenBonus;

        Maturity(final double oxygenBonus) {
            this.oxygenBonus = oxygenBonus;
        }

        /**
         * Returns the oxygen bonus associated with this maturity level.
         *
         * @return bonus oxygen value
         */
        public double getOxygenBonus() {
            return oxygenBonus;
        }

        /**
         * Returns the next maturity level, or {@code null} if the plant reached its last stage.
         *
         * @return the next maturity level or {@code null}
         */
        public Maturity nextLevel() {
            return switch (this) {
                case Young -> Mature;
                case Mature -> Old;
                case Old -> null;
            };
        }
    }

    /**
     * Constructs a new plant based on the provided input data.
     *
     * @param plantInput the input data defining this plant
     */
    public Plant(final PlantInput plantInput) {
        super(plantInput.getName(), plantInput.getMass());
        type = PlantType.valueOf(plantInput.getType());
    }

    /**
     * Returns the string representation of this plant's type.
     *
     * @return plant type name
     */
    @Override
    public String getType() {
        return type.name();
    }

    /**
     * Computes the total oxygen generated by the plant,
     * based on its type and maturity bonus.
     *
     * @return generated oxygen amount
     */
    public double generateOxygen() {
        return type.getOxygenPlant() + age.getOxygenBonus();
    }

    /**
     * Increases the plant's growth level. Once the growth level reaches 1,
     * the plant advances to the next maturity level.
     */
    public void growPlant() {
        growthLevel += GROWTH_INCREMENT;
        if (growthLevel == 1d) {
            growthLevel -= 1d;
            age = age.nextLevel();
        }
    }

    /**
     * Returns the probability of the plant becoming stuck,
     * expressed as a value between 0 and 1.
     *
     * @return stuck probability in decimal form
     */
    public double getStuck() {
        return type.getStuckProbability() / PERCENT_NORMALIZATION;
    }

    /**
     * Indicates whether the plant has reached the end of its life cycle.
     *
     * @return {@code true} if the plant is dead, otherwise {@code false}
     */
    public boolean isDead() {
        return age == null;
    }

    /**
     * Returns a description used when scanning this plant.
     *
     * @return a plant-specific scan message
     */
    @Override
    public String getScanResult() {
        return "The scanned object is a plant.";
    }
}
